# Generated by Django 5.0.7 on 2024-07-11 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_id', models.CharField(max_length=50, unique=True)),
                ('cafe_pw', models.CharField(max_length=100)),
                ('cafe_name', models.CharField(max_length=100)),
                ('ceo_name', models.CharField(max_length=100)),
                ('cafe_time', models.CharField(max_length=100)),
                ('ceo_tel', models.CharField(max_length=20)),
                ('cafe_region', models.CharField(max_length=100)),
                ('cafe_tel', models.CharField(max_length=20)),
                ('cafe_address', models.CharField(default='Default Address', max_length=255)),
                ('seats_count', models.IntegerField()),
                ('empty_seats', models.IntegerField()),
                ('cafe_photo', models.ImageField(blank=True, null=True, upload_to='cafe_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempuser_tel', models.CharField(max_length=20)),
                ('temp_pw', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_pw', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.CharField(max_length=50, unique=True)),
                ('plug', models.BooleanField()),
                ('backseat', models.BooleanField()),
                ('seat_start_time', models.DateTimeField(blank=True, null=True)),
                ('seat_use_time', models.DateTimeField(blank=True, null=True)),
                ('seats_no', models.CharField(max_length=128)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='situapp.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_time', models.DateTimeField()),
                ('number_of_people', models.IntegerField()),
                ('seat_status', models.CharField(choices=[('available', 'Available'), ('reserve', 'Reserve'), ('occupied', 'Occupied')], max_length=10)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='situapp.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='situapp.user')),
            ],
        ),
    ]
