# Generated by Django 5.0.7 on 2024-07-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('requesting', 'Requesting')], max_length=20),
        ),
    ]
