# Generated by Django 5.0.7 on 2024-07-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situapp', '0002_remove_reservation_status_alter_seat_seat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='noneuser_tel',
        ),
    ]
