# Generated by Django 5.0.7 on 2024-07-20 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situapp', '0003_remove_reservation_noneuser_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('liked', models.BooleanField(default=False)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='situapp.cafe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='situapp.user')),
            ],
        ),
    ]
