# Generated by Django 5.0.7 on 2024-07-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_status',
            field=models.CharField(choices=[('available', '사용 가능'), ('occupied', '사용중'), ('requesting', '예약 진행중'), ('reserved', '예약 완료')], max_length=20),
        ),
    ]
