# Generated by Django 5.0.7 on 2024-07-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_seat_seat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='empty_seats',
        ),
    ]
