# Generated by Django 5.0.4 on 2024-07-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_cafe_empty_seats_cafe_email_cafe_is_active_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0003_remove_cafe_empty_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cafe'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_reservations', to='accounts.cafe'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cafe'),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='empty_seats',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_permissions_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='Cafe',
        ),
    ]
