# Generated by Django 5.0.6 on 2024-07-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_pw',
            new_name='password',
        ),
    ]
