# Generated by Django 5.0.7 on 2024-07-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempuser_tel', models.CharField(max_length=20)),
                ('temp_pw', models.CharField(max_length=100)),
            ],
        ),
    ]
