# Generated by Django 5.0.4 on 2024-07-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_cafe_empty_seats_cafe_email_cafe_is_active_and_more'),
        ('dashboard', '0002_alter_favorite_unique_together_alter_favorite_cafe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='accounts.cafe'),
        ),
    ]
