# Generated by Django 5.0.4 on 2024-07-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_cafe_empty_seats_cafe_email_cafe_is_active_and_more'),
        ('reservations', '0002_reservation_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cafe'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='accounts.cafe'),
        ),
    ]
